#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.80                        #
#------------------------------------------------------------------------------#

WRKDIR = `pwd`


CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
RCFLAGS = 
LIBDIR = 
LIB = -framework GLUT -framework OpenGL -framework Cocoa
LDFLAGS =

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS)
OBJDIR_RELEASE = objs
DEP_RELEASE = 
OUT_RELEASE = ../bin/icosphere

OBJ_RELEASE = $(OBJDIR_RELEASE)/Bmp.o $(OBJDIR_RELEASE)/Icosphere.o $(OBJDIR_RELEASE)/main.o

#all: release
all: perc

clean: clean_release after_release

before_release: 
	test -d ../bin || mkdir -p ../bin
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

perc: ocupacion.o before_release out_release after_release


#main.o: main.cpp
#	$(CXX) -c -o main.o main.cpp



#release: before_release out_release after_release perc


out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE) ocupacion.o
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE) ocupacion.o $(LDFLAGS_RELEASE) $(LIB_RELEASE)

ocupacion.o: ocupacion.cpp
	$(CXX) -c -o ocupacion.o ocupacion.cpp

$(OBJDIR_RELEASE)/Bmp.o: Bmp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Bmp.cpp -o $(OBJDIR_RELEASE)/Bmp.o

$(OBJDIR_RELEASE)/Icosphere.o: Icosphere.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Icosphere.cpp -o $(OBJDIR_RELEASE)/Icosphere.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf ../bin
	rm -rf $(OBJDIR_RELEASE)
	rm *.o

.PHONY: before_release after_release clean_release

